In [1]:
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import numpy as np
import os


In [2]:
import sys
# sys.path.insert(1, str(Path().resolve().parent) + r'\Shared_Functionality\Preprocessing\Preprocessing Functions')
# sys.path.append('/Shared_Functionality/Preprocessing/Preprocessing Functions/')
sys.path.insert(0, "/Users/scarr/MIMS/tensor-hero/Shared_Functionality/Preprocessing/Preprocessing Functions/")
# Shared_Functionality/Preprocessing/Preprocessing Functions/audio_functions.py
# /Users/scarr/MIMS/tensor-hero/Shared_Functionality/Preprocessing/Preprocessing Functions/audio_functions.py
from audio_functions import compute_mel_spectrogram
song_path = "/Users/scarr/MIMS/files_tensorhero/Training Data/Unprocessed/Facelift Pack 2/Affiance - Call to the Warrior [Chezy]/song.ogg"


In [4]:
spec = compute_mel_spectrogram(song_path)

In [5]:
spec.shape

(512, 26823)

In [23]:
# spec_real
# plt.plot(spec[0][:500])
for i in range(0,143):
    for j in spec[:,i]:
        if j != -80:
            print(i)
spec[:,0]


array([-80., -80., -80., -80., -80., -80., -80., -80., -80., -80., -80.,
       -80., -80., -80., -80., -80., -80., -80., -80., -80., -80., -80.,
       -80., -80., -80., -80., -80., -80., -80., -80., -80., -80., -80.,
       -80., -80., -80., -80., -80., -80., -80., -80., -80., -80., -80.,
       -80., -80., -80., -80., -80., -80., -80., -80., -80., -80., -80.,
       -80., -80., -80., -80., -80., -80., -80., -80., -80., -80., -80.,
       -80., -80., -80., -80., -80., -80., -80., -80., -80., -80., -80.,
       -80., -80., -80., -80., -80., -80., -80., -80., -80., -80., -80.,
       -80., -80., -80., -80., -80., -80., -80., -80., -80., -80., -80.,
       -80., -80., -80., -80., -80., -80., -80., -80., -80., -80., -80.,
       -80., -80., -80., -80., -80., -80., -80., -80., -80., -80., -80.,
       -80., -80., -80., -80., -80., -80., -80., -80., -80., -80., -80.,
       -80., -80., -80., -80., -80., -80., -80., -80., -80., -80., -80.,
       -80., -80., -80., -80., -80., -80., -80., -8

In [379]:
path_new_notes = '../../files_tensorhero/Training Data/Processed/Facelift Pack 2/Stevie Ray Vaughan and Double Trouble - Texas Flood [xX760Xx]/notes.npy'
notes = np.load((path_new_notes))


In [380]:
print(notes[400:800])

[  0.   0.   0.   0.   0.   0.   0.   0.   0. 197.   0.   0.   0.   0.
   0.   0.   0.   0.  13.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0. 104.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0. 197.   0.   0.   0.   0.
   0.   0.   0.  96.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 189.
   0.   0.   0.   0.   0.   0.   0. 219.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  12.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0. 

In [381]:
for i in range(0,len(notes)):
    if notes[i] in [31.62,93,124,155,186,217]:
        notes[i] = 31
array_mod = notes % 31



[0. 0. 0. ... 0. 0. 0.]


In [386]:
small = array_mod[800:1200]
small = small.astype(int)
print(small)

[ 0  0  0 14  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0 13  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 13  0  0  0  0
  0  0  0  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  3  0  1  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 25  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 25  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 25  0  0  0
  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0

In [390]:
nb_classes = 32
targets = np.array([small]).reshape(-1)
one_hot_targets = np.eye(nb_classes)[targets]
mat = one_hot_targets.T
mat[14]

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [360]:
mat.shape

(32, 400)

In [391]:

def make_time_and_note_array(matrix):
    rotate = matrix.T.astype(int)
    output = []
    for i in range(0,rotate.shape[0]):
        time = np.zeros(400).astype(int)
        time[i] = 1
        new = np.concatenate((time,rotate[i]))
        output.append(new)
    output = np.array(output)
    return output



In [403]:
x = make_time_and_note_array(mat)
x[:,400:].shape
trans = x[:,400:].T
trans.shape

# nb_classes = 31
# targets = np.array([small]).reshape(-1)
# one_hot_targets = np.eye(nb_classes)[targets]
# mat = one_hot_targets.T

a = [trans[i] * i for i in range(0,len(trans))]
a = np.array(a)


In [405]:
b = a.sum(axis = 0)
b == small

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [20]:
from torchtext.legacy.data import Field
from torchtext.datasets import Multi30k



In [10]:
def tokenize_eng(text):
    return [tok.text for tok in spacy_eng.tokenizer(text)]
english = Field(
    tokenize=tokenize_eng, lower=True, init_token="<sos>", eos_token="<eos>"
)

In [18]:
train_data, valid_data, test_data = Multi30k.splits(
    exts=(".en"), fields=(english)
)
english.build_vocab(train_data, max_size=10000, min_freq=2)

AttributeError: 'function' object has no attribute 'splits'