In [1]:
from pathlib import Path
import sys
import numpy as np
import pandas as pd 
import os

In [2]:
#create training set with original index 
full_array = np.load('full_array.npy')
df = pd.DataFrame(full_array, columns =['exp', 'hard', 'med','easy'] )
df_train = df.loc[df['exp'] != 0.0]
df_train['index'] = df_train.index
df_train

exp  hard  med  easy
0      0.0   0.0  0.0   0.0
1      0.0   0.0  0.0   0.0
2      0.0   0.0  0.0   0.0
3      0.0   0.0  0.0   0.0
4      0.0   0.0  0.0   0.0
...    ...   ...  ...   ...
57025  0.0   0.0  0.0   0.0
57026  0.0   0.0  0.0   0.0
57027  0.0   0.0  0.0   0.0
57028  0.0   0.0  0.0   0.0
57029  0.0   0.0  0.0   0.0

[57030 rows x 4 columns]

In [4]:
#expert to hard df
df_train_1 = df_train[['index', 'exp', 'hard']]
df_train_1

index    exp  hard
180      180  218.0   1.0
274      274  218.0   1.0
299      299  218.0   1.0
7249    7249    1.0   1.0
7349    7349  218.0   1.0
...      ...    ...   ...
56679  56679    4.0   4.0
56799  56799    3.0   3.0
56859  56859    2.0   2.0
56919  56919    4.0   4.0
56979  56979    5.0   5.0

[1416 rows x 3 columns]

In [25]:
# df to np array
exp_to_hard_arr = df_train_1.to_numpy()
exp_to_hard_arr.shape

(1416, 3)

In [9]:
#expert unique notes
exp_uniques, counts = np.unique(df_train['exp'], return_counts=True)
exp_uniques
#counts

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,  10.,  11.,  13.,  14.,
        15.,  16.,  17.,  19.,  22.,  23.,  24.,  26., 218.])

In [111]:
# empty matrix from exp to hard
#exp_to_hard_matrix = np.empty((len(exp_uniques), len(exp_uniques)+1))
exp_to_hard_matrix = np.zeros(shape=(20, 21))
exp_to_hard_matrix.shape
  

(20, 21)

In [99]:
#out put a dictionary of all the transformed notes
filter_indices = {}

for j in exp_uniques:

    for i in range(1416) :
        if exp_to_hard_arr[i][1] == j:
            
            if j not in filter_indices:
                filter_indices[j] = list()
            
            filter_indices[j].append(exp_to_hard_arr[i][2])



In [121]:
#fill in the probablity matrix
for i in exp_uniques:
        
    uniques, counts = np.unique(filter_indices[int(i)], return_counts=True) 

    for u in range(len(uniques)):
        u_val = uniques[u]
        #print(int(u_val))
        prob = (counts / len(filter_indices[i]))[u]
        exp_to_hard_matrix[i][int(u_val)] = prob
    

IndexError: index 22 is out of bounds for axis 0 with size 21

In [120]:
exp_to_hard_matrix

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.48044693, 0.16759777, 0.33519553, 0.01675978, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.48262548, 0.003861  , 0.38996139, 0.1042471 , 0.01930502,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.32472325, 0.        , 0.04059041, 0.55719557, 0.06642066,
        0.01107011, 0.        , 0.        , 0.       

In [113]:
for u in range(len(uniques)):
    u_val = uniques[u]
    #print(int(u_val))
    prob = (counts / len(filter_indices[1]))[u]
    exp_to_hard_matrix[1][int(u_val)] = prob
    

0
0.48044692737430167
-----
1
0.16759776536312848
-----
2
0.33519553072625696
-----
3
0.01675977653631285
-----


In [122]:
exp_uniques

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,  10.,  11.,  13.,  14.,
        15.,  16.,  17.,  19.,  22.,  23.,  24.,  26., 218.])

In [127]:
uniques, counts = np.unique(filter_indices[10], return_counts=True)
print(uniques)
print(counts)

[ 0.  2.  3.  4. 10. 13.]
[ 6  3 10  2  9  4]
