In [5]:
import numpy as np
import torch
import random

In [3]:
# Numpy array
em_table = np.random.uniform(0,1,(32,12000))
new_array = (em_table/em_table.sum(axis=0))
new_array.sum(axis=0)

array([1., 1., 1., ..., 1., 1., 1.])

In [6]:
# tensor
emission_table = torch.rand((32,12000))
new_emTable = (emission_table/emission_table.sum(axis=0))
new_emTable.sum(axis=0)

tensor([1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000])

In [7]:
new_emTable.shape

torch.Size([32, 12000])

In [14]:
np.random.randint(0,12000,4)

array([11166,  1333,  9031,  4571])

In [16]:
def onset_label(onset, spectrogram=None):
    '''
    Function that takes in 1D onset array and spectrogram and labels each onset with the spectrogram that most closely
    matches the emission probability table

    INPUTS: 1D Onset Array , computed spectrogram
    OUTPUTS: 1D Array of same length as onset array corresponding to column indices of emission probability table 
    '''
    # X will probably need to be determined by spectrogram clusters , set locally just to highlight
    X = 12000
    return np.random.randint(0,X,len(onset))
    

In [17]:
onset_example = np.array([5,2,5,7,9,3,5])
label = onset_label(onset_example)