This notebook is meant to investigate the proportion of our training examples that have no notes, and systematic differences between their respective spectrograms

We'll use the small amount of training data I have loaded onto this computer to investigate

In [ ]:
from pathlib import Path
import os
import numpy as np

train_path = Path.cwd().parent / 'Training_Data' / 'training_ready' / 'train'
song_paths = [train_path / x for x in os.listdir(train_path)]
notes_parents = [x / 'notes' for x in song_paths]
specs_parents = [x / 'spectrograms' for x in song_paths]

notes_paths = []
specs_paths = []

for i in range(len(notes_parents)):
    for notes_dir in [notes_parents[i] / x for x in os.listdir(notes_parents[i])]:
        notes_paths.extend([notes_dir / x for x in os.listdir(notes_dir)])
    for specs_dir in [specs_parents[i] / x for x in os.listdir(specs_parents[i])]:
        specs_paths.extend([specs_dir / x for x in os.listdir(specs_dir)])

In [13]:
no_notes_paths = []
no_specs_paths = []
full_notes_paths = []
full_specs_paths = []

for idx, notes_path in enumerate(notes_paths):
    notes = np.load(notes_path)
    if notes.shape[0] == 2:
        no_notes_paths.append(notes_path)
        no_specs_paths.append(specs_paths[idx])
    else:
        full_notes_paths.append(notes_path)
        full_specs_paths.append(specs_paths[idx])

print(f'len no_notes: {len(no_notes_paths)}')
print(f'len full_notes: {len(full_notes_paths)}')
print(f'{len(no_notes_paths)*100/len(notes_paths):.2f}% of training examples have no notes')

len no_notes: 203
len full_notes: 1805
10.11% of training examples have no notes


In [32]:
spec = np.load(specs_paths[0])
print(f'spec shape: {spec.shape}')
print(f'spec: {spec}')
print(np.min(spec))
print(np.max(spec))
# for i in range(512):
#     print(spec[i,:])
print(np.sum(spec.astype(np.float32)))

spec shape: (512, 400)
spec: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
0.0
0.1885
152.82224
