In [2]:
import numpy as np
from prototyping import *

In [3]:
# 1D array (not limited to 4s slots, rather full song)
# Index: Time (in miliseconds)
# Values: integer between 31 and 0 for keys played 


# TESTING spec_to_in_spec_list
test_spec = np.random.randint(80, size=(512, 820))
test_spec = test_spec*(-1)
in_spec_list = spec_to_in_spec_list(test_spec)
in_spec_list


# TESTING notes_to_out_seq_list
test_notes1 = np.zeros(420)
test_notes1[2] = 1
test_notes1[3] = 29

test_notes2 = np.random.choice(32, 420)

test_notes3 = np.zeros(420)
test_notes3[2] = 31
test_notes3[390] = 28
test_notes3[399] = 18
test_notes3[411] = 24

In [4]:
# Spectrogram
# Dimensions: 512 x length of song in ms

test_spec = np.random.randint(80, size=(512, 820))
test_spec = test_spec*(-1)
print(test_spec)

[[-16  -3 -21 ... -12 -51 -16]
 [-52 -34 -71 ... -24  -9 -15]
 [-77  -6 -43 ... -76 -50 -78]
 ...
 [-18 -57 -62 ... -27 -57 -78]
 [-70 -50 -33 ... -68 -57 -64]
 [-78 -61 -43 ... -69 -37 -39]]


In [5]:
in_spec_list = spec_to_in_spec_list(test_spec)
print(len(in_spec_list))
print(in_spec_list[1].shape)

2
(512, 400)


In [6]:
out_seq_list1 = notes_to_out_seq_list(test_notes1)
out_seq_list1
out_seq_list2 = notes_to_out_seq_list(test_notes2)
out_seq_list2
out_seq_list3 = notes_to_out_seq_list(test_notes3)
out_seq_list3


print(out_seq_list1[0].shape)
print(out_seq_list2[0].shape)

(432,)
(432,)


In [7]:
# TESTING out_seq_list_to_notes
processed_notes1 = out_seq_list_to_notes(out_seq_list1)
processed_notes2 = out_seq_list_to_notes(out_seq_list2)
processed_notes3 = out_seq_list_to_notes(out_seq_list3)
processed_notes1
processed_notes2
processed_notes3

print(processed_notes1.shape, test_notes1.shape)
print((processed_notes1[:400] == test_notes1[:400]).all())

print((processed_notes2[:400] == test_notes2[:400]).all())
print(processed_notes2.shape, test_notes2.shape)

print((processed_notes3[:400] == test_notes3[:400]).all())
print(processed_notes3.shape, test_notes3.shape)


print("-----------")
#for i in range(800):
#    print(i, processed_notes2[i], test_notes2[i])

(400,) (420,)
True
True
(800,) (420,)
True
(800,) (420,)
-----------
